### ISSUE TITLE
Docs report debian stretch as testing

### ISSUE THREAD

**Issue by Mrifk** [canonical-docs/snappy-docs#266] opened 2017-12-19 09:23 UTC
https://docs.snapcraft.io/core/install-debian

Stretch is no longer in testing, it is stable now.

**Comment by matthewpaulthomas** [comment] 2018-02-20 11:31
Thanks for the report, @Mrifk. This is a duplicate of #146 which has been fixed.

**Closed by matthewpaulthomas** 2018-02-20 11:31 UTC
Labels: Status: Triaged
