### ISSUE TITLE
Rust Tutorial  "snapcraft" Command Fails to Execute 

### ISSUE THREAD

**Issue by DigiBrkr** [canonical-docs/snappy-docs#298] opened 2018-01-03 15:54 UTC
I am working on a QA task for the Google Code-in: [ rust snap creation tutorial](https://docs.snapcraft.io/build-snaps/rust) and I believe I have found an issue. When the user runs the`snapcraft` command, it fails to execute and displays the following error message: 
 ```
error: failed to load source for a dependency on `parity-ui-precompiled`

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git#5b3e3150

```
 This problem appears to be happening because on or about December 12, 2017 the files located in the GitHub repository `paritytech/js-precompiled` were moved. See [here](https://github.com/paritytech/js-precompiled). I assume that the error would be resolved  by updating the appropriate files with the new location.

The full log is attached bellow. 

Thank you for looking at my issue! 

[rust.log](https://github.com/canonical-docs/snappy-docs/files/1600639/rust.log)

**Comment by matthewpaulthomas** [comment] 2018-02-20 11:25
Thanks for your report, @DigiBrkr. This is a duplicate of #268.

**Closed by matthewpaulthomas** 2018-02-20 11:25 UTC
