### ISSUE TITLE
Debian 'stretch' mentioned as testing release

### ISSUE THREAD

**Issue by kraju** [canonical-docs/snappy-docs#282] opened 2017-12-29 12:44 UTC
https://docs.snapcraft.io/core/install-debian

> On Debian snapd is available as part of the testing (currently ‘stretch’) and unstable (‘sid’) versions. It is currently not available in any stable version but will be soon.

Current testing is called "buster", "stretch" is stable nowadays.

**Comment by matthewpaulthomas** [comment] 2018-02-20 11:31
Thanks for the report, @kraju. This is a duplicate of #146 which has been fixed.

**Closed by matthewpaulthomas** 2018-02-20 11:31 UTC
